### ISSUE TITLE
Is the GradeScope for non-CMU students is available yet?

### ISSUE THREAD

**Issue by ziyi-yan** [cmu-db/bustub#111]
This is a great course on databases. Thanks for making all these course materials available in public.

As the project 0 and 1 have passed the due date, I really hope I can test my solution against additional test cases to learn more about these projects.

**Comment by apavlo** [comment]
@ziyi-yan Try access code: 5VX7JZ

**Comment by ziyi-yan** [comment]
Thanks, @apavlo! I tried and succeed in entering the course. But I got a weird result for my submission of project 0. It reports that `Test Failed: Test was not run. Please check the autograder!`. I'm sure that I get the default basic test cases passed on my local machine.

The screenshot is pasted below.
<img width="1552" alt="截屏2020-10-16 下午12 05 12" src="https://user-images.githubusercontent.com/44582639/96212116-95f95580-0fa8-11eb-9892-3c7aa9712dcd.png">

**Comment by ziyi-yan** [comment]
The autograder of project 1 works like a charm. Project 0 is not that important. Thanks again, @apavlo!

**Comment by apavlo** [comment]
@ziyi-yan Your P0 fails the memory check.

**Comment by ziyi-yan** [comment]
There are still not-run tests when I got the `test_memory_safety` passed.
<img width="1552" alt="截屏2020-10-19 下午3 53 13" src="https://user-images.githubusercontent.com/44582639/96417010-5db17b80-1223-11eb-9eea-2050d62332c1.png">

**Comment by apavlo** [comment]
Look at the output. You are failing `make check-format`.

**Comment by DiligentPanda** [comment]
@ziyi-yan , I think the problem is you probably submit github branch instead of just a zip file with only p0_starter.h as required in the following section:
![image](https://user-images.githubusercontent.com/25078430/96668844-9d48a680-138e-11eb-9c2b-21c79f7beb64.png)

(I guess ) The autograder copies some files from you submission to its default code repository and use its own base codes, makefile, format-checking settings to compile the project. What probably goes wrong in your case (also mine:joy:) is that the default clang-tidy setting enables modernize-use-auto(you can search it in your output from test_build) and the codes in b_plus_tree.cpp fail to pass it. This setting is however disabled in your local .clang-tidy file(by a minus prefix, you can check this file in your root directory.).

So, just follow the instructions in the project page, you will get another 100, I believe!

**Comment by lambdafate** [comment]
@DiligentPanda , You are right.  I have the same problem, and i fix it by uploading the zip file.  thanks for the help :)

**Comment by minleminzui** [comment]
I also encountered the same question. I fixed it. The main reason is that I used the "move" function in header file <utility>. I forgot to include it in my file before.
![image](https://user-images.githubusercontent.com/54172054/155330521-9d96b503-1590-4728-839a-03233f794552.png)
