### ISSUE TITLE
BufferPoolManager.NewPage spec is unclear if the pages returned must be pinned

### ISSUE THREAD

**Issue by sitano** [cmu-db/bustub#34]
It is unclear from the spec if the pages returned from BufferPoolManager.NewPage must be pinned.

Actually, if they are not the test would fail (as any previously allocated page becomes victimized instantly), from what I can conclude they must be?

And of course, it is funny to return a pointer to a newly allocated page which was concurrently evicted even before the method returned.

It is also unclear whether the new page must be marked as _dirty_.

**Comment by tcalasans** [comment]
I am not part of the staff, but I will give my 2 cents.

>It is unclear from the spec if the pages returned from BufferPoolManager.NewPage must be pinned.
>
> Actually, if they are not the test would fail (as any previously allocated page becomes victimized 
> instantly), from what I can conclude they must be?

It is kind of implicit in the specs, I think. The fact that a pointer to a page is being returned by the method indicates that the method expects the user to use the page, as in FetchPageImpl, which means the page should remain pinned until the user of the bufferpool signals with Unpin.

>It is also unclear whether the new page must be marked as dirty.

Good point. I actually just fixed a bug in my solution regarding that. Because the current version of disk manager merely increments page counter upon allocation of new page, it can potentially create a problem: the newly-created page, which is placed in the buffer, is not in the disk (thus, file has not been expanded), but if your implementation assumes that newly-created page is not dirty (due to the semantics of it), then unpinning that page later will not cause a flush, and a subsequent fetch to that page will cause disk_manage to err because file is too small (since page was never flushed).

It seems that new pages should either be:
- dirty by default (more efficient)
- written to disk in 'NewPageImpl', by default, and not dirty (less efficient)

**Comment by iwanttbepowerful** [comment]
@sitano Do you understand the second test case of buffer_pool_manager_test.cpp?

**Comment by sitano** [comment]
> Do you understand the second test case of buffer_pool_manager_test.cpp?

@iwanttbepowerful the `TEST(BufferPoolManagerTest, DISABLED_SampleTest) {` one?

**Comment by iwanttbepowerful** [comment]
> > Do you understand the second test case of buffer_pool_manager_test.cpp?
> 
> @iwanttbepowerful the `TEST(BufferPoolManagerTest, DISABLED_SampleTest) {` one?
> 
> It that's the one, then yes. Ask what you part you don't.

Hi, bro. Thanks for your reply. I understood the test case.

**Comment by skyzh** [comment]
Fixed in this year.

https://github.com/cmu-db/bustub/blob/4df5b13f317c86e1f0058135ede3a219b26f3578/src/include/buffer/buffer_pool_manager_instance.h#L66-L68
