### ISSUE TITLE
make fails with various compile errors

### ISSUE THREAD

**Issue by abdulrahman86** [cmu-db/bustub#39]
I am following the steps on README to build the project. When I run `make` I get the following error

`<project_root_dir>/src/include/storage/page/page.h:70:39: error: expected ‘,’ before ‘)’ token
   static_assert(sizeof(page_id_t) == 4)`

Also get 
`<project_root_dir>/src/include/storage/page/page.h:70:39: error: expected string-literal before ‘)’ token`

And 

`/src/include/storage/page/page.h:71:35: error: expected ‘,’ before ‘)’ token
   static_assert(sizeof(lsn_t) == 4);`

When I comment out the above two lines and try to make then there are a whole bunch other compile errors that I get, some of which are very similar.

**Comment by abdulrahman86** [comment]
Ok so looks like `static_assert(sizeof(page_id_t) == 4)` requires a `message` which was eliminated in c++17. so perhaps cmake is not building for the right c++ target? I see `set(CMAKE_CXX_STANDARD 17) `  in `<project_root_dir>/CMakeLists.txt` file. Shouldn't that take care of compiling and building my code for the right c++ target?

**Comment by tcalasans** [comment]
I had that problem. What I did:
- Ran build_support/packages.sh
- From that script I learned I needed to update my ubuntu to version 18...
- Updated ubuntu
- Re-ran packages.sh to completion
- Error went away
- Now I have an error when I run `make check-tests`

> /usr/bin/ld: ../lib/libgmock_main.a(gmock_main.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC

**Comment by lmwnshn** [comment]
@abdulrahman86 We only support C++17. CMake only passes build flags to the compiler it finds, your installed compiler itself must support C++17. 

@tcalasans You need to clean the build folder out.

If either of you are in the class, stop by my office hours on Saturday, otherwise I can only offer limited support for build issues that are caused by your setup. It should work for a clean Ubuntu18.04 image, and it works for me and for a number of students I've seen so far.

Feel free to reopen this if you can demonstrate a reproducible error on a clean Ubuntu18.04 install.
