### ISSUE TITLE
HashUtil::HashBytes produces different values depending on cpu architecture

### ISSUE THREAD

**Issue by mpurins** [cmu-db/bustub#738]
Hello,

I am following along 'Intro to Database Systems' and when doing project0 I was having my head boil when `BasicTest2` test was not passing but everything appeared to be correct.

I did investigation and traced down the issue to this line in `HashUtil::HashBytes`.
https://github.com/cmu-db/bustub/blob/0ba573cd59dc9dd915169cf9f1557d568e520cab/src/include/common/hash_util.h#L36 

When xoring with `bytes[i]` which is of type `char` there is implicit/automatic conversion happening from `char` to `size_t` (which is unsigned integer) and that works differently depending if that `char` is signed vs unsigned. Note that on x86 `char` is signed and such conversion is done by sign-extending of value, but on arm machines `char` is unsigned and then this conversion is done by zero-extending of value and this difference leads to different values in x86 vs arm machines.

One of such values which has different hashes on x86 vs arm is `200` and here are replication/demo in godbolt
- unsigned version which produces `15668040698880 ` -- https://godbolt.org/z/MroET7Ybf
- signed version which produces `4471945099923683303 ` -- https://godbolt.org/z/hcchWjqKf

Simplest solution for this could be just adding `-fsigned-char` to compiler flags (or at minimum documenting somewhere to add this flag for arm mac/pc), but in proper fix I think it would make more sense to use unsigned char or std::byte when working stream of bytes.

**Comment by connortsui20** [comment]
This should have been resolved by now, please let us know if it was not!

**Comment by epaulson** [comment]
I don't think this has been resolved and I had the same issue. My platform is a Mac with an M1 Max CPU, in an Ubuntu 22.04 VM. (It is completely fair if you say that combination is not a supported platform, but I'm using a VM so I did not have to downgrade my existing llvm install in Homebrew)

Things seemed off when trying to debug BasicTest2, enough so that I came looking at the GH issues, and I found this one.  I added `-fsigned-char` to the compiler flags and BasicTest2 started to pass. 

I believe I am on the latest code:

```bash
ubuntu@ubuntu:~/development/bustub/bustub-private$ git log
commit 570547381a71e6494cc02ee457f3163bdf004eb6 (HEAD -> master, origin/master, origin/HEAD)
Author: Kunle <67528514+unw9527@users.noreply.github.com>
Date:   Sat Dec 7 14:51:57 2024 -0500

    remove MacOS 12 (Monterey) CI (#784)
    
    remove macos 12 CI
```
and the Ubuntu VM I am using is from here:
https://mac.getutm.app/gallery/ubuntu-20-04

with `build_support/packages.sh` applied

I think my HLL code is correct, though this is the first time I've written any C++ in nearly 20 years so I make no promises.
